import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { existsSync } from 'node:fs';
import * as yaml from 'js-yaml';
import { randomBytes } from 'node:crypto';
import { Paths } from '@minecraft-docker/shared';

/**
 * API Access Mode
 * Determines how the Admin API can be accessed
 */
export type ApiAccessMode =
  | 'internal' // Docker network only (default)
  | 'api-key' // External access with API key
  | 'ip-whitelist' // IP-based access
  | 'api-key-ip' // Both API key and IP
  | 'open'; // No authentication (development only)

/**
 * Admin Configuration structure stored in YAML
 */
export interface AdminConfig {
  version: string;
  api: {
    access_mode: ApiAccessMode;
    port: number;
    api_key: string | null;
    allowed_ips: string[];
  };
  console: {
    enabled: boolean;
    port: number;
  };
  initialized_at: string;
}

/**
 * Default configuration values
 */
const DEFAULT_CONFIG: AdminConfig = {
  version: '1.0',
  api: {
    access_mode: 'internal',
    port: 3001,
    api_key: null,
    allowed_ips: [],
  },
  console: {
    enabled: true,
    port: 3000,
  },
  initialized_at: new Date().toISOString(),
};

/**
 * AdminConfigManager
 * Manages .mcctl-admin.yml configuration file
 */
export class AdminConfigManager {
  private readonly configPath: string;

  constructor(rootDir?: string) {
    const paths = new Paths(rootDir);
    this.configPath = join(paths.root, '.mcctl-admin.yml');
  }

  /**
   * Get the configuration file path
   */
  get path(): string {
    return this.configPath;
  }

  /**
   * Check if admin service is already initialized
   */
  isInitialized(): boolean {
    return existsSync(this.configPath);
  }

  /**
   * Load existing configuration
   */
  async load(): Promise<AdminConfig | null> {
    if (!this.isInitialized()) {
      return null;
    }

    try {
      const content = await readFile(this.configPath, 'utf-8');
      return yaml.load(content) as AdminConfig;
    } catch {
      return null;
    }
  }

  /**
   * Save configuration to file
   */
  async save(config: AdminConfig): Promise<void> {
    // Ensure directory exists
    const dir = dirname(this.configPath);
    if (!existsSync(dir)) {
      await mkdir(dir, { recursive: true });
    }

    const yamlContent = yaml.dump(config, {
      indent: 2,
      lineWidth: -1,
      quotingType: '"',
      forceQuotes: false,
    });

    // Add header comment
    const header = `# mcctl Admin Service Configuration
# Generated by: mcctl admin init
# Do not edit this file manually unless you know what you are doing.
#
# API Access Modes:
#   internal     - Docker network only (default, most secure)
#   api-key      - External access with API key
#   ip-whitelist - IP-based access control
#   api-key-ip   - Requires both API key and IP match
#   open         - No authentication (development only, NOT for production)
#
`;

    await writeFile(this.configPath, header + yamlContent, 'utf-8');
  }

  /**
   * Create a new configuration with specified options
   */
  async create(options: {
    accessMode: ApiAccessMode;
    apiKey?: string | null;
    allowedIps?: string[];
    apiPort?: number;
    consolePort?: number;
    consoleEnabled?: boolean;
  }): Promise<AdminConfig> {
    const config: AdminConfig = {
      ...DEFAULT_CONFIG,
      api: {
        access_mode: options.accessMode,
        port: options.apiPort ?? DEFAULT_CONFIG.api.port,
        api_key: options.apiKey ?? null,
        allowed_ips: options.allowedIps ?? [],
      },
      console: {
        enabled: options.consoleEnabled ?? DEFAULT_CONFIG.console.enabled,
        port: options.consolePort ?? DEFAULT_CONFIG.console.port,
      },
      initialized_at: new Date().toISOString(),
    };

    await this.save(config);
    return config;
  }

  /**
   * Generate a new API key with mctk_ prefix
   */
  static generateApiKey(): string {
    // Generate 32 bytes of random data and encode as base64url
    const randomPart = randomBytes(32)
      .toString('base64url')
      .replace(/[^a-zA-Z0-9]/g, '')
      .substring(0, 40);
    return `mctk_${randomPart}`;
  }

  /**
   * Validate an API key format
   */
  static isValidApiKey(key: string): boolean {
    return /^mctk_[a-zA-Z0-9]{20,}$/.test(key);
  }
}
