// ecosystem.config.js
// =============================================================================
// PM2 Ecosystem Configuration for Minecraft Management Console
// =============================================================================
// This file is auto-generated by 'mcctl console init' command.
// It configures PM2 to run mcctl-api and mcctl-console services.
//
// Usage:
//   pm2 start ecosystem.config.js     # Start all services
//   pm2 stop all                      # Stop all services
//   pm2 restart all                   # Restart all services
//   pm2 logs                          # View logs
//   pm2 status                        # Check status
//
// Installation:
//   npm install -g pm2
//   pm2 startup                       # Configure auto-start on boot
//   pm2 save                          # Save current process list
// =============================================================================

module.exports = {
  apps: [
    {
      name: 'mcctl-api',
      script: 'node_modules/@minecraft-docker/mcctl-api/dist/index.js',
      cwd: process.env.MCCTL_ROOT || '.',
      env: {
        NODE_ENV: 'production',
        PORT: 5001,
        HOST: '0.0.0.0',
        MCCTL_ROOT: process.env.MCCTL_ROOT || '.',
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_memory_restart: '500M',
    },
    {
      name: 'mcctl-console',
      script: 'node_modules/@minecraft-docker/mcctl-console/.next/standalone/platform/services/mcctl-console/server.js',
      cwd: process.env.MCCTL_ROOT || '.',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        HOSTNAME: '0.0.0.0',
        MCCTL_API_URL: 'http://localhost:5001',
        MCCTL_ROOT: process.env.MCCTL_ROOT || '.',
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_memory_restart: '500M',
    },
  ],
};
